config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get '/admin', to: redirect('/admin/categories')
  namespace :admin do
    resources :categories
    resources :products
  end

  resources :categories, only: [:index, :show], path: '/'
  resources :products, only: [:show] do
    resources :reviews, only: [:create, :edit, :update, :destroy]
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user
      if user.is_admin?
        can :manage, Product
        can :manage, Category
        can :manage, Review
      else
        can :create, Review
      end
    end
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :products, dependent: :destroy

  validates :name, presence: true
  validates :name, uniqueness: { case_sensitive: false }

  def should_generate_new_friendly_id?
    name_changed?
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  has_many :reviews, dependent: :destroy

  validates :title, presence: true
  validates_presence_of :category
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product
  belongs_to :user
  validates :message, presence: true
  validates_presence_of :product
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reviews
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :email, format: { with: /@/}
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  respond_to :html
  authorize_resource
  before_action :find_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def show
    redirect_to edit_admin_category_path
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new category_params
    if @category.save
      redirect_to admin_categories_path
    else
      respond_with :admin, @category
    end
  end

  def update
    if @category.update category_params
      redirect_to admin_categories_path
    else
      respond_with :admin, @category
    end
  end

  def destroy
    @category.destroy
    respond_with :admin, @category
  end

private

  def find_category
    @category = Category.friendly.find params[:id]
  end

  def category_sparams
    params.require(:category).permit(:name)
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  respond_to :html
  authorize_resource
  before_action :find_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all
  end

  def show
    redirect_to edit_admin_product_path
  end

  def new
    @product = Product.new
  end

  def edit

  end

  def create
    @product = Product.new product_params
    if @product.save
      redirect_to admin_products_path
    else
      respond_with :admin, @product
    end
  end

  def update
    if @product.update product_params
      redirect_to admin_products_path
    else
      respond_with :admin, @product
    end
  end

  def destroy
    @product.destroy
    respond_with :admin, @product
  end

private

  def find_product
    @product = Product.find params[:id]
  end

  def product_params
    params.require(:product).permit(:title, :description, :category_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @products = Product.all
    render :show
  end

  def show
    @category = Category.friendly.find params[:id]
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def show
    @product  = Product.find params[:id]
    @category = @product.category
    @review   = @product.reviews.new
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  respond_to :html
  authorize_resource
  before_action :find_product, only: [:create, :edit, :update, :destroy]
  before_action :find_review,  only: [:edit, :update, :destroy]

  def create
    @review = @product.reviews.new review_params
    @review.user = current_user
    if @review.save
      redirect_to product_path @product
    else
      render 'products/show'
    end
  end

  def update
    if @review.update review_params
      redirect_to product_path @product
    else
      render :edit
    end
  end

  def destroy
    @review.destroy
    redirect_to product_path @product
  end

private

  def find_product
    @product = Product.find params[:product_id]
  end

  def find_review
    @review = Review.find params[:id]
  end

  def review_params
    params.require(:review).permit(:message, :product)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/categories/_form.html.haml
= simple_form_for [:admin, @category] do |f|
  = f.error_notification
  .row= f.input :name, wrapper_html: { class: 'col-md-14' }
  = f.submit class: 'btn btn-info'

app/views/admin/categories/edit.html.haml
- content_for :title do
  Editing Category

%h1 Editing Category
%br

= render 'form'

app/views/admin/categories/index.html.haml
- content_for :title do
  All categories

%h1 All categories
%br

- if @categories.size > 0
  %table.table.table-striped
    %thead
      %tr
        %th.col-xs-10 Name
        %th.col-xs-2

    %tbody
      - @categories.each do |category|
        %tr
          %td= category.name
          %td.text-right
            = link_to 'edit', edit_admin_category_path(category)
            |
            = link_to 'destroy', [:admin, category], method: :delete, data: { confirm: 'Are you sure?' }

= link_to 'new category', new_admin_category_path, class: 'btn btn-info'

app/views/admin/categories/new.html.haml
- content_for :title do
  New Category

%h1 New Category
%br

= render 'form'

app/views/admin/products/_form.html.haml
= simple_form_for [:admin, @product] do |f|
  = f.error_notification
  .row= f.input :title, wrapper_html: { class: 'col-md-14' }
  .row= f.input :description, wrapper_html: { class: 'col-md-14' }, input_html: { rows: 5 }
  .row= f.input :category_id, collection: Category.all, include_blank: false, wrapper_html: { class: 'col-md-6' }
  = f.submit class: 'btn btn-info'

app/views/admin/products/edit.html.haml
- content_for :title do
  Editing Product

%h1 editing product
%br

= render 'form'

app/views/admin/products/index.html.haml
- content_for :title do
  Listing Products

%h1 all products
%br

- if @products.size > 0
  %table.table.table-striped
    %thead
      %tr
        %th.col-xs-3 title
        %th.col-xs-4 description
        %th.col-xs-3 category
        %th.col-xs-2

    %tbody
      - @products.each do |product|
        %tr
          %td= product.title
          %td= product.description
          %td= product.category.name
          %td.text-right
            = link_to 'edit', edit_admin_product_path(product)
            |
            = link_to 'destroy', [:admin, product], method: :delete, data: { confirm: 'Are you sure?' }

= link_to 'new product', new_admin_product_path, class: 'btn btn-info'

app/views/admin/products/new.html.haml
- content_for :title do
  New Product

%h1 New Product
%br

= render 'form'

app/views/application/_messages.html.erb
<% if flash.now[:notice] %>
  <div class="flakes-message success"><%= flash[:notice] %></div>
<% end %>

<% if flash.now[:error] %>
  <div class="flakes-message error"><%= flash[:error] %></div>
<% end %>

app/views/application/_mobile_top_bar.html.erb
<div class="flakes-mobile-top-bar">
  <a href="" class="logo-wrap">
    <%= image_tag asset_path('flakes/img/site-wide/logo.png'), height: '30px' %>
  </a>

  <a href="" class="navigation-expand-target">
    <%= image_tag asset_path('flakes/img/site-wide/navigation-expand-target.png'), height: "26px" %>
  </a>
</div>

app/views/application/_navigation.html.erb
<div class="flakes-navigation">
  <a href="index.html" class="logo">
    <%= image_tag asset_path('flakes/img/site-wide/logo.png'), width: '120' %>
  </a>

  <ul>
    <li class="title">Category Title</li>
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to 'Products', products_path %></li>
    <% if logged_in? %>
      <li><%= link_to "Users", users_path %></li>
    <% else %>
      <li><%= link_to "Log In", login_path %></li>
    <% end %>
  </ul>

  <% if logged_in? %>
    <p class="foot">
      Hello <b><%= current_user.name %></b><br>
      <a href="">My Account</a> &bullet;
      <%= link_to "Log Out", logout_path %>
    </p>
  <% end %>
</div>

app/views/application/index.html.erb
<% provide :title, "Home" %>

<h1>Catalog App</h1>
<p>This is the basic structure of the catalog app.</p>

app/views/categories/_list.html.haml
.col-xs-3
  %h3 Categories
  %br
  %ul.nav.nav-pills.nav-stacked
    %li{class: ('active' unless locals[:category])}
      = link_to 'All', categories_path
    - Category.all.each do |category|
      %li{class: ('active' if category == locals[:category])}
        = link_to category.name, category_path(category)

app/views/categories/show.html.haml
- content_for :title do
  - if @products.present? or not @category.present?
    all products
  - else
    products by
    = @category.name

.row
  = render 'list', locals: {category: @category}
  .col-xs-9
    %h3 products
    %br
    - if @category.present? or @products.present?
      - @products = @category.products unless @products.present?
      - @products.each do |product|
        .panel.panel-default
          .panel-heading
            %h3.panel-title
              = link_to product.title, product_path(product)
          .panel-body= product.description

app/views/layouts/_head.html.haml
= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.2/css/bootstrap.min.css'
= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/hover.css/1.0.8/css/hover.css'
= stylesheet_link_tag 'application', media: 'all'
= csrf_meta_tags

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-default{role: "navigation"}
  .container
    .navbar-header
      = link_to 'catalog', categories_path, class: 'navbar-brand'

    .collapse.navbar-collapse.navbar-ex1-collapse
      %ul.nav.navbar-nav.navbar-right
        - if Rails.env.development?
          %li{style: 'margin: 19px'}
        - if user_signed_in?
          %li
            = link_to 'logout', destroy_user_session_path, method: :delete
        - else
          %li
            = link_to 'login', new_user_session_path
          %li
            = link_to 'sign up', new_user_registration_path

app/views/layouts/_scripts.html.haml
= javascript_include_tag 'application'
= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.1/js/bootstrap.min.js'
= yield :javascripts

app/views/layouts/application.html.haml
%html
  %head
    %title= content_for?(:title) ? yield(:title) + ' - Catalog' : 'Catalog'
    = render 'layouts/head'
  %body
    = render 'layouts/navbar'
    .container
      //.p#notice= notice
      = yield
    = render 'layouts/scripts'

app/views/products/_feedback.html.haml
- if can? :create, Review
  %h4 Leave your feedback for this product
  = render 'reviews/form'
  %hr

.list-group
  - @product.reviews.each do |review|
    - unless review.id.nil?
      .list-group-item
        .row-action-primary
          %i.mdi-communication-message
        .row-content
          .action-secondary
            %i.mdi-material-info
          by
          = review.user && review.user.email || 'guest'
          - if can? :manage, Review
            .pull-right
              [
              = link_to 'edit', edit_product_review_path(@product, review)
              |
              = link_to 'delete', product_review_path(@product, review), method: :delete, data: { confirm: 'Are you sure?' }
              ]
          %p.list-group-item-text= review.message
      .list-group-separator

app/views/products/show.html.haml
- content_for :title do
  =@product.title

.row
  = render 'categories/list', locals: {category: @product.category}
  .col-xs-9
    %h3= @product.title
    %br
    %p
      %small= @product.description
    %hr
    = render 'products/feedback'

app/views/reviews/_form.html.haml
= simple_form_for @review, url: @review.persisted? ? product_review_path(@product, @review) : product_reviews_path(@product) do |f|
  = f.error_notification
  = f.input :message, label: false, input_html: { rows: 5 }
  = f.submit 'add review', class: 'btn btn-info'

app/views/reviews/edit.html.haml
- content_for :title do
  Editing Review

%h1 editing review
%br

= render 'form'

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>